name: branch-protection
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.ref_name }} 
on:
  push:
    branches: ['develop','main']
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - run: echo "push"
